clusters = primary, standby

primary.bootstrap.servers = primary-kafka:9092
standby.bootstrap.servers = standby-kafka:9094

primary->standby.enabled = true

primary->standby.topics = .*
primary->standby.groups = .*

# Make internal topics createable in single-node test clusters
config.storage.topic = mm2-configs
offset.storage.topic = mm2-offsets
status.storage.topic = mm2-status

config.storage.replication.factor = 1
offset.storage.replication.factor = 1
status.storage.replication.factor = 1

replication.factor = 1

emit.checkpoints.enabled = true
sync.group.offsets.enabled = true