clusters = primary, standby

primary.bootstrap.servers = primary-kafka:9092
standby.bootstrap.servers = standby-kafka:9094

primary->standby.enabled = true

primary->standby.topics = .*
primary->standby.groups = .*

replication.factor = 1

emit.checkpoints.enabled = true
sync.group.offsets.enabled = true