FROM apache/kafka:4.0.0

WORKDIR /kafka

ENV CLASSPATH=/kafka/libs/*
# Copy your custom MM2 jar to override
COPY Kafka/kafka/core/build/libs/*.jar   /kafka/libs/
COPY Kafka/kafka/clients/build/libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/build/libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/mirror/build/libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/basic-auth-extension/build/libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/basic-auth-extension/build/dependant-libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/api/build/dependant-libs/*.jar /kafka/libs/
COPY Kafka/kafka/connect/api/build/libs/*.jar /kafka/libs/

# Copy Kafka scripts
COPY Kafka/kafka/bin/connect-mirror-maker.sh /kafka/bin/connect-mirror-maker.sh


# Copy your config
COPY config/mm2.properties /kafka/config/

# Run MirrorMaker 2
ENTRYPOINT ["bin/connect-mirror-maker.sh"]
CMD ["/kafka/config/mm2.properties"]