FROM eclipse-temurin:17-jdk-jammy

# Set Kafka home
ENV KAFKA_HOME=/opt/kafka
ENV PATH=$KAFKA_HOME/bin:$PATH

# Copy your built Kafka distribution
COPY Kafka/kafka/core/build/distributions/kafka_2.13-4.0.0.tgz /opt/

# Extract Kafka
RUN cd /opt && tar -xzf kafka_2.13-4.0.0.tgz && mv kafka_2.13-4.0.0 kafka

# Copy MM2 config
COPY config/mm2.properties /opt/kafka/config/mm2.properties

WORKDIR /opt/kafka

# Run MirrorMaker 2
CMD ["bin/connect-mirror-maker.sh", "config/mm2.properties"]