FROM eclipse-temurin:17-jdk-jammy

ENV KAFKA_HOME=/opt/kafka
ENV PATH=$KAFKA_HOME/bin:$PATH

COPY Kafka/kafka/core/build/distributions/kafka_2.13-4.0.0.tgz /opt/

RUN cd /opt && tar -xzf kafka_2.13-4.0.0.tgz && mv kafka_2.13-4.0.0 kafka

RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*

COPY config/mm2.properties /opt/kafka/config/mm2.properties

WORKDIR /opt/kafka

CMD ["sh", "-c", "echo 'Waiting for Kafka...' && while ! nc -z primary-kafka 9092; do sleep 2; done && while ! nc -z standby-kafka 9092; do sleep 2; done && echo 'Starting MirrorMaker 2...' && bin/connect-mirror-maker.sh config/mm2.properties"]